version: '3.8'
services:
  wordpress:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
  db:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=brief10
      - MYSQL_ROOT_PASSWORD=123@Password
    volumes:
      - db-wp:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    ports: 
      - 8080:80
volumes:
  db-wp: